version: "3.7"

services:
  store-database:
    image: postgres:13.3
    container_name: store_db
    ports:
      - "5432:5432"
    volumes:
      - ~/app/postgresql:/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=store_db
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d store_db"]
      interval: 10s
      timeout: 5s
      retries: 5


  store-service:
    container_name: store-service
    build: .
    ports:
      - "8085:8085"
    environment:
      DATABASESERVER_PORT: "5432:5432"
      SPRING_DATASOURCE_URL: jdbc:postgresql://store-database:5432/store_db
      SPRING_DATASOURCE_USER: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - store-database
    networks:
      - backend

networks:
  backend:
    driver: bridge