server:
  port: 8085

spring:
  application:
    name: store-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/store_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: password
    tomcat:
      initial-size: 6
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 5
